source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PinchableImageView_Example', :exclusive => true do
  pod 'PinchableImageView', :path => '../'
end

target 'PinchableImageView_Tests', :exclusive => true do
  pod 'PinchableImageView', :path => '../'

  
end
